# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/


theme = "blowfish"
baseURL = "https://laterre.dev"
defaultContentLanguage = "ko"

title = "Laterre Dev"

[author]
  name = "Laterre"
  image = "img/laterre_blog_profile.png"
  headline = "Develop Experience @Backend Developer"
  bio = "✨ 좋은 개발 경험이란 무엇일지 항상 고민합니다."
  links = [
    { github = "https://github.com/laterre39" },
    { stack-overflow = "https://stackoverflow.com/users/20004273/laterre" },
    { x-twitter = "https://twitter.com" },
    { email = "mailto:changil.kim@laterre.dev" },
  ]

[params]
  dateFormat = "2006-01-02"
  logo = "img/laterre_logo_white.png"
  secondaryLogo = "img/laterre_logo_black.png"
  description = "Develop Experience @Backend Developer"
  copyright = "© { year } laterre.dev"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

# robots.txt
enableRobotsTXT = true
paginate = 10
summaryLength = 30

buildDrafts = false
buildFuture = false

#googleAnalytics = "G-

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"

# sitemap 생성
[sitemap]
# always, hourly daily, weekly, monthly, yearly, never
changefreq = "always"
filename = "sitemap.xml"
priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "posts"
        weight = 10