# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 40


# -- Social Menu --

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/laterre39"
  weight = 100

[[main]]
  identifier = "stack-overflow"
  pre = "stack-overflow"
  url = "https://stackoverflow.com/users/20004273/laterre"
  weight = 200

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com"
  weight = 300

[[main]]
  identifier = "email"
  pre = "email"
  url = "mailto:laterre39@naver.com"
  weight = 400


# -- Footer Menu --

[[footer]]
   name = "Github"
   url = "https://github.com/laterre39"
   weight = 10

[[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 20

[[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 30