# example netlify.toml
[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.120.3"
  TZ = “Asia/Seoul”

[context.production.environment]
  TZ = “Asia/Seoul”

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = false

  [plugins.inputs]
    enable = false